"""
FractureAI PDF Report Generator
=================================
Generates professional medical PDF reports with scan results,
heatmap images, and AI-based recovery suggestions.

Supports two backends:
  1. fpdf2 (preferred) — lightweight, pure-Python PDF library
  2. reportlab (fallback) — robust PDF generation if fpdf2 fails

If neither library is importable (e.g. Python 3.13 C-extension issues),
a minimal plain-text PDF fallback is used so the app can still start.
"""

import os
from datetime import datetime

# ── Try to import a PDF backend ──────────────────────────────
_BACKEND = None

try:
    from fpdf import FPDF
    _BACKEND = "fpdf"
except (ImportError, OSError) as _e:
    print(f"[FractureAI] fpdf2 unavailable ({_e}), trying reportlab...")

if _BACKEND is None:
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.units import mm
        from reportlab.lib.colors import HexColor
        from reportlab.pdfgen import canvas as rl_canvas
        _BACKEND = "reportlab"
    except (ImportError, OSError) as _e:
        print(f"[FractureAI] reportlab unavailable ({_e}), PDF reports will use text fallback")

print(f"[FractureAI] PDF backend: {_BACKEND or 'text-fallback'}")


# ═══════════════════════════════════════════════════════════════
#  FPDF2 backend
# ═══════════════════════════════════════════════════════════════
if _BACKEND == "fpdf":

    class MedicalReport(FPDF):
        """Custom PDF class with medical report styling."""

        def __init__(self):
            super().__init__()
            self.set_auto_page_break(auto=True, margin=25)

        def header(self):
            """Draw report header with branding."""
            # Background bar
            self.set_fill_color(15, 23, 42)  # Dark slate
            self.rect(0, 0, 210, 35, "F")

            # Brand name
            self.set_font("Helvetica", "B", 20)
            self.set_text_color(56, 189, 248)  # Cyan accent
            self.set_y(8)
            self.cell(0, 10, "FractureAI", ln=False, align="L")

            # Subtitle
            self.set_font("Helvetica", "", 9)
            self.set_text_color(148, 163, 184)
            self.set_y(18)
            self.cell(0, 6, "AI-Powered Bone Fracture Detection System", ln=False, align="L")

            # Report date on right
            self.set_font("Helvetica", "", 9)
            self.set_text_color(148, 163, 184)
            self.set_y(8)
            self.cell(0, 10, f"Report Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=False, align="R")

            self.ln(30)

        def footer(self):
            """Draw report footer."""
            self.set_y(-20)
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(100, 116, 139)
            self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")
            self.set_y(-14)
            self.cell(0, 10, "CONFIDENTIAL - For Medical Use Only | Generated by FractureAI", align="C")

        def section_title(self, title):
            """Print a styled section title."""
            self.set_font("Helvetica", "B", 13)
            self.set_text_color(30, 41, 59)
            self.cell(0, 10, title, ln=True)
            # Underline
            self.set_draw_color(56, 189, 248)
            self.set_line_width(0.8)
            self.line(self.get_x(), self.get_y(), self.get_x() + 60, self.get_y())
            self.ln(4)

        def info_row(self, label, value, highlight=False):
            """Print a label-value row."""
            self.set_font("Helvetica", "B", 10)
            self.set_text_color(71, 85, 105)
            self.cell(55, 7, f"{label}:", ln=False)

            self.set_font("Helvetica", "", 10)
            if highlight:
                self.set_text_color(239, 68, 68)  # Red for alerts
            else:
                self.set_text_color(30, 41, 59)
            self.cell(0, 7, str(value), ln=True)

        def severity_badge(self, severity):
            """Print a colored severity badge."""
            colors = {
                "Low": (34, 197, 94),       # Green
                "Medium": (234, 179, 8),     # Yellow
                "High": (239, 68, 68),       # Red
                "N/A": (148, 163, 184),      # Gray
            }
            r, g, b = colors.get(severity, (148, 163, 184))

            self.set_font("Helvetica", "B", 10)
            self.set_text_color(71, 85, 105)
            self.cell(55, 7, "Severity:", ln=False)

            self.set_fill_color(r, g, b)
            self.set_text_color(255, 255, 255)
            self.set_font("Helvetica", "B", 9)
            badge_width = self.get_string_width(f"  {severity}  ") + 4
            self.cell(badge_width, 7, f"  {severity}  ", ln=True, fill=True)
            self.set_text_color(0, 0, 0)


# ═══════════════════════════════════════════════════════════════
#  Public API
# ═══════════════════════════════════════════════════════════════

def generate_pdf_report(scan_data, user_data, output_path):
    """
    Generate a complete medical PDF report.

    Args:
        scan_data: Dictionary with scan results
            {
                "fracture_detected": bool,
                "confidence": float,
                "severity": str,
                "fracture_type": str,
                "recovery_suggestion": str,
                "doctor_recommendation": str,
                "body_part": str,
                "original_image": str (path),
                "heatmap_image": str (path),
                "scanned_at": str,
            }
        user_data: Dictionary with user info
            {
                "full_name": str,
                "email": str,
                "username": str,
            }
        output_path: Path to save the PDF file

    Returns:
        Path to the generated PDF
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    if _BACKEND == "fpdf":
        return _generate_fpdf(scan_data, user_data, output_path)
    elif _BACKEND == "reportlab":
        return _generate_reportlab(scan_data, user_data, output_path)
    else:
        return _generate_text_fallback(scan_data, user_data, output_path)


# ── fpdf2 implementation ─────────────────────────────────────

def _generate_fpdf(scan_data, user_data, output_path):
    """Generate PDF using the fpdf2 backend."""
    pdf = MedicalReport()
    pdf.alias_nb_pages()
    pdf.add_page()

    # ── Patient Information ──────────────────────────────────
    pdf.section_title("Patient Information")
    pdf.info_row("Patient Name", user_data.get("full_name", "N/A"))
    pdf.info_row("Email", user_data.get("email", "N/A"))
    pdf.info_row("Scan Date", scan_data.get("scanned_at", datetime.now().strftime("%Y-%m-%d %H:%M")))
    pdf.info_row("Body Part", scan_data.get("body_part", "Unknown"))
    pdf.ln(6)

    # ── AI Diagnosis Results ─────────────────────────────────
    pdf.section_title("AI Diagnosis Results")
    status = "FRACTURE DETECTED" if scan_data.get("fracture_detected") else "NO FRACTURE DETECTED"
    pdf.info_row("Diagnosis", status, highlight=scan_data.get("fracture_detected", False))
    pdf.info_row("Confidence", f"{scan_data.get('confidence', 0):.1f}%")
    pdf.severity_badge(scan_data.get("severity", "N/A"))
    pdf.info_row("Fracture Type", scan_data.get("fracture_type", "N/A"))
    pdf.ln(6)

    # ── X-Ray Images ─────────────────────────────────────────
    pdf.section_title("X-Ray Analysis")
    original_img = scan_data.get("original_image", "")
    if original_img and os.path.exists(original_img):
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(0, 6, "Original X-Ray:", ln=True)
        try:
            pdf.image(original_img, x=15, w=80)
        except Exception:
            pdf.cell(0, 6, "[Image could not be loaded]", ln=True)
        pdf.ln(4)

    heatmap_img = scan_data.get("heatmap_image", "")
    if heatmap_img and os.path.exists(heatmap_img):
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(0, 6, "AI Heatmap (Grad-CAM):", ln=True)
        try:
            pdf.image(heatmap_img, x=15, w=80)
        except Exception:
            pdf.cell(0, 6, "[Heatmap could not be loaded]", ln=True)
        pdf.ln(6)

    # ── Recovery & Recommendations ───────────────────────────
    pdf.add_page()
    pdf.section_title("AI Recovery Suggestions")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(30, 41, 59)
    suggestion = scan_data.get("recovery_suggestion", "No specific suggestions available.")
    pdf.multi_cell(0, 6, suggestion)
    pdf.ln(6)

    pdf.section_title("Recommended Specialist")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(30, 41, 59)
    doctor_rec = scan_data.get("doctor_recommendation", "Please consult an orthopedic specialist.")
    pdf.multi_cell(0, 6, doctor_rec)
    pdf.ln(6)

    # ── Disclaimer ───────────────────────────────────────────
    pdf.section_title("Disclaimer")
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(100, 116, 139)
    disclaimer = (
        "This report is generated by FractureAI, an AI-powered diagnostic assistance tool. "
        "The results are for informational purposes only and should NOT be used as a "
        "substitute for professional medical advice, diagnosis, or treatment. "
        "Always seek the advice of a qualified healthcare provider with any questions "
        "regarding a medical condition. AI predictions may not be 100% accurate."
    )
    pdf.multi_cell(0, 5, disclaimer)

    pdf.output(output_path)
    return output_path


# ── reportlab implementation ─────────────────────────────────

def _generate_reportlab(scan_data, user_data, output_path):
    """Generate PDF using the reportlab backend."""
    c = rl_canvas.Canvas(output_path, pagesize=A4)
    width, height = A4
    y = height - 40 * mm

    # Header
    c.setFillColor(HexColor("#38bdf8"))
    c.setFont("Helvetica-Bold", 22)
    c.drawString(20 * mm, y, "FractureAI")
    y -= 7 * mm
    c.setFillColor(HexColor("#94a3b8"))
    c.setFont("Helvetica", 9)
    c.drawString(20 * mm, y, "AI-Powered Bone Fracture Detection System")
    y -= 15 * mm

    def _section(title):
        nonlocal y
        c.setFillColor(HexColor("#1e293b"))
        c.setFont("Helvetica-Bold", 13)
        c.drawString(20 * mm, y, title)
        y -= 3 * mm
        c.setStrokeColor(HexColor("#38bdf8"))
        c.setLineWidth(0.8)
        c.line(20 * mm, y, 80 * mm, y)
        y -= 7 * mm

    def _row(label, value):
        nonlocal y
        c.setFillColor(HexColor("#475569"))
        c.setFont("Helvetica-Bold", 10)
        c.drawString(20 * mm, y, f"{label}:")
        c.setFillColor(HexColor("#1e293b"))
        c.setFont("Helvetica", 10)
        c.drawString(75 * mm, y, str(value))
        y -= 6 * mm

    _section("Patient Information")
    _row("Patient Name", user_data.get("full_name", "N/A"))
    _row("Email", user_data.get("email", "N/A"))
    _row("Scan Date", scan_data.get("scanned_at", datetime.now().strftime("%Y-%m-%d %H:%M")))
    _row("Body Part", scan_data.get("body_part", "Unknown"))
    y -= 6 * mm

    _section("AI Diagnosis Results")
    status = "FRACTURE DETECTED" if scan_data.get("fracture_detected") else "NO FRACTURE DETECTED"
    _row("Diagnosis", status)
    _row("Confidence", f"{scan_data.get('confidence', 0):.1f}%")
    _row("Severity", scan_data.get("severity", "N/A"))
    _row("Fracture Type", scan_data.get("fracture_type", "N/A"))
    y -= 6 * mm

    _section("Recovery Suggestions")
    c.setFont("Helvetica", 9)
    c.setFillColor(HexColor("#1e293b"))
    suggestion = scan_data.get("recovery_suggestion", "No specific suggestions available.")
    for line in suggestion.split("\n")[:15]:
        if y < 30 * mm:
            c.showPage()
            y = height - 30 * mm
        c.drawString(20 * mm, y, line[:100])
        y -= 5 * mm

    y -= 6 * mm
    c.setFont("Helvetica-Oblique", 8)
    c.setFillColor(HexColor("#64748b"))
    c.drawString(20 * mm, y, "CONFIDENTIAL - For Medical Use Only | Generated by FractureAI")

    c.save()
    return output_path


# ── text fallback ────────────────────────────────────────────

def _generate_text_fallback(scan_data, user_data, output_path):
    """Generate a simple text file as a last-resort fallback."""
    status = "FRACTURE DETECTED" if scan_data.get("fracture_detected") else "NO FRACTURE DETECTED"
    content = f"""
========================================
        FractureAI Medical Report
========================================

Patient: {user_data.get('full_name', 'N/A')}
Email:   {user_data.get('email', 'N/A')}
Date:    {scan_data.get('scanned_at', datetime.now().strftime('%Y-%m-%d %H:%M'))}
Body:    {scan_data.get('body_part', 'Unknown')}

--- AI Diagnosis ---
Diagnosis:     {status}
Confidence:    {scan_data.get('confidence', 0):.1f}%
Severity:      {scan_data.get('severity', 'N/A')}
Fracture Type: {scan_data.get('fracture_type', 'N/A')}

--- Recovery Suggestions ---
{scan_data.get('recovery_suggestion', 'No specific suggestions available.')}

--- Doctor Recommendation ---
{scan_data.get('doctor_recommendation', 'Please consult an orthopedic specialist.')}

--- Disclaimer ---
This report is AI-generated and should NOT replace professional medical advice.

CONFIDENTIAL - Generated by FractureAI
"""
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)
    return output_path
